#!/bin/bash

# Labels
yabai -m space 1 --label home
yabai -m space 2 --label slack
yabai -m space 3 --label work

# Layout
yabai -m config layout bsp

# Padding and Gaps
yabai -m config top_padding    30
yabai -m config bottom_padding 30
yabai -m config left_padding   30
yabai -m config right_padding  30
yabai -m config window_gap     20

# Mouse
yabai -m config mouse_modifier          fn
yabai -m config mouse_action1           move
yabai -m config mouse_action2           resize
yabai -m config focus_follows_mouse     autoraise

# Window
yabai -m config window_topmost          on
yabai -m config window_shadow           float

## Opacity
yabai -m config window_opacity          off
yabai -m config active_window_opacity   1.0
yabai -m config normal_window_opacity   0.85

## Border
yabai -m config window_border               on
yabai -m config window_border_width         4
yabai -m config window_border_radius        -1.0
yabai -m config active_window_border_color 0xffAA6D39
yabai -m config normal_window_border_color 0xff2E4272
yabai -m config insert_window_border_color 0xff2D8632
### BORDER-DEFAULT
#yabai -m config active_window_border_color 0xff775759
#yabai -m config normal_window_border_color 0xff505050
#yabai -m config insert_window_border_color 0xffd75f5f

## Status Bar
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Menlo:Bold:14.0"
yabai -m config status_bar_icon_font         "Menlo:Regular:14.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9 10
yabai -m config status_bar_power_icon_strip  🔋 🔌
yabai -m config status_bar_space_icon        ⭐️
yabai -m config status_bar_clock_icon        ⊚

# Exclusions
## Float system preferences 
yabai -m rule --add label=system_pref_float \
  app='System Preferences' \
  manage=off

## Float pritunl
yabai -m rule --add label=pritunl_float \
  app='Pritunl' \
  manage=off

echo "yabai configuration loaded.."
