# @@@@@@@@   @@@@@@   @@@  @@@  @@@@@@@    @@@@@@@ #
# @@@@@@@@  @@@@@@@   @@@  @@@  @@@@@@@@  @@@@@@@@ #
#      @@!  !@@       @@!  @@@  @@!  @@@  !@@      #
#     !@!   !@!       !@!  @!@  !@!  @!@  !@!      #
#    @!!    !!@@!!    @!@!@!@!  @!@!!@!   !@!      #
#   !!!      !!@!!!   !!!@!!!!  !!@!@!    !!!      #
#  !!:           !:!  !!:  !!!  !!: :!!   :!!      #
# :!:           !:!   :!:  !:!  :!:  !:!  :!:      #
#  :: ::::  :::: ::   ::   :::  ::   :::   ::: ::: #
# : :: : :  :: : :     :   : :   :   : :   :: :: : #

# interactive-only config

## Better man paging
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

export EDITOR='nvim'

source $HOME/.aliases

# Interactive Terminal Prompt
eval-cache starship init zsh

# Smart directory changing
eval-cache zoxide init zsh
