# ZSHRC

## Vars
export DOTFILES="$HOME/.dotfiles"
export EDITOR='nvim'


## Development Environment
test -f ~/.dev && source ~/.dev
export PATH="$PATH:/Users/jared/.dotnet/tools"


## Linux Brew
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"


## Bat Manpages colour
export MANPAGER="sh -c 'col -bx | bat -l man -p'"


## Starship Prompt
eval "$(starship init zsh)"

### Oh My Zsh
#export ZSH=$HOME/.oh-my-zsh
#source $ZSH/oh-my-zsh.sh

eval "$(zoxide init zsh)"

## Personal Functions and Aliases
export PATH="$DOTFILES/bin:$PATH"
source $HOME/.aliases

## Fzf and Fd
export FZF_DEFAULT_COMMAND='fd --type f'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
alias fp="fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'"
