#!/bin/bash

#Colours for Echos L=Light, D=Dark, B=Bold
NC='\033[0m' # No Color
WHITE='\033[0;37m'
B_WHITE='\033[1;37m'
PURPLE='\033[0;35m'
LB_PURPLE='\033[1;95m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
L_BLUE='\033[0;94m'
LB_BLUE='\033[1;94m'
D_BLUE='\033[1;34m'
B_CYAN='\033[1;36m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
L_GREEN='\033[0;92m'
LB_GREEN='\033[1;92m'
RED='\033[0;31m'
LB_RED='\033[1;91m'

#ALIASES
# Specific locations
alias dot="cd $DOTFILES"
alias funcs="cd $DOTFILES/bin"

#Git
alias glog="git log --graph --oneline --decorate --all"
alias huh="git-st"
alias greset="git checkout HEAD --"
alias gundo="git reset --soft HEAD~1"
alias todos="git-branch-todos"

#Other
alias yo="ping 1.1.1.1"
alias ,="ssh"
alias k="kubectl"
alias mongo='aws sso login --profile development-sc001 && eval $(aws configure export-credentials --profile development-sc001 --format env) && /Applications/MongoDB\ Compass.app/Contents/MacOS/MongoDB\ Compass &'

#Overwrites
alias ls='exa --color=auto'

# Functions inline the commands so are run
#  in the same context as execution

mkcd() {
  test -e "$1" && if ! [[ -d "$1" ]]; then
    >&2 echo "File exists and is not a directory"
    return 1
  fi

  mkdir -p "$1"
  cd "$1"
}

# better aws
alias aws='r=$RANDOM;u=("https://youtu.be/7_EeCkHs-e0?si=4NBODuMPLaChNNrO" "https://youtu.be/ebkAM2_zsEk?si=llPYNScSfLYc2N6a" "https://youtu.be/2x2jAuSXMOg?si=DjhCv5EGK2YLZ1kn" "https://youtu.be/GeLLNABXFZo?si=ZyFoy8SS4Q4XD-4H");i=$((r%4));c=${u[$i]:-${u[2]}};x=$((r%10));if [ $x -eq 0 ];then open "$c";say jeffery bezos has approved your A W S session;fi;command aws'
